{% set version = "2.1.0" %}

package:
  name: bintrees
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bintrees/bintrees-{{ version }}.zip
  sha256: eae2732fae01b24eb17b3943721945c1ec88b2126e081c5c785ce448924d3f96

build:
  number: 0
  skip: True  # [py>36]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  imports:
    - bintrees
    - bintrees.bintree
    - bintrees.avltree
    - bintrees.rbtree

about:
  home: https://pypi.python.org/pypi/bintrees/2.0.7
  license: MIT
  license_file: LICENSE.txt
  summary: 'Binary-, RedBlack- and AVL-Trees in Python and Cython'

  # The remaining entries in this section are optional, but recommended
  description: |
    Use sortedcontainers instead: https://pypi.python.org/pypi/sortedcontainers
    This Classes are much slower than the built-in dict class, but all iterators/generators
    yielding data in sorted key order. Trees can be uses as drop in replacement 
    for dicts in most cases. 
  doc_url: https://pypi.python.org/pypi/bintrees/2.0.7
  dev_url: https://github.com/mozman/bintrees

extra:
  recipe-maintainers:
    - pvanheus
