# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UBLMcnxvDARkXmmTzt/RMrM6HSyJXy5tR0eyoZt6mmEyOU6WcpiNyuGnicPTLMFZM4gHVzRLWlenjjtiKDtBeoQgskHrPjVDnGLcnngIEW8rZwcMH/5EnYIk2/AAf9oOKrLTuYvjuU0NXP9K52mxric6Td9aWtEfPjmqcqeG/wmMiA8S6p3NqsLED49Y7AQq+C7DpzC8ou1MsNg8wM4GG1yzqVhwPSgPPqhoWwlUUenJ7AW1YDBuKxnRgga6dKXC2jy7OIf4mVcfCaUqrJ4+RrU0dxJpL7xch6b9Kfcrn8l7AJtJeeD8vYKyBXsV611+9138JSnuAa+Gze9k1AvIbwvy5dA8NGqhX9ThnN6+rj2ldRnfRi2Sh++18mp7/U0jd9ncBvJD0KL1SytlZ1NE7BWoSZNgwNXl6o8DKIRua0jySPXg+JjSxeW26ClHE8aF6ENeB91rY5PqjuACgUSn6fgNoib5ynmjXluhgsHRDOO+R2nM2awpu9jYvJEQU6guXWKrGs7sfSBmA4zqoGen8UgX/xKZr5+YJh+oeVtAUs8nB07M275Br3o0xn2Z6iDFLxJPD6x9/oN+KdcogzrvCFJ9QhLLL26CttvoURRaQ5I//qP2JAUpuTfKBWB3rxQqsdK94kD9ofltwg4N5fbUsfZsPleUuQULAxtdCBya2KY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
