appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UBLMcnxvDARkXmmTzt/RMrM6HSyJXy5tR0eyoZt6mmEyOU6WcpiNyuGnicPTLMFZM4gHVzRLWlenjjtiKDtBeoQgskHrPjVDnGLcnngIEW8rZwcMH/5EnYIk2/AAf9oOKrLTuYvjuU0NXP9K52mxric6Td9aWtEfPjmqcqeG/wmMiA8S6p3NqsLED49Y7AQq+C7DpzC8ou1MsNg8wM4GG1yzqVhwPSgPPqhoWwlUUenJ7AW1YDBuKxnRgga6dKXC2jy7OIf4mVcfCaUqrJ4+RrU0dxJpL7xch6b9Kfcrn8l7AJtJeeD8vYKyBXsV611+9138JSnuAa+Gze9k1AvIbwvy5dA8NGqhX9ThnN6+rj2ldRnfRi2Sh++18mp7/U0jd9ncBvJD0KL1SytlZ1NE7BWoSZNgwNXl6o8DKIRua0jySPXg+JjSxeW26ClHE8aF6ENeB91rY5PqjuACgUSn6fgNoib5ynmjXluhgsHRDOO+R2nM2awpu9jYvJEQU6guXWKrGs7sfSBmA4zqoGen8UgX/xKZr5+YJh+oeVtAUs8nB07M275Br3o0xn2Z6iDFLxJPD6x9/oN+KdcogzrvCFJ9QhLLL26CttvoURRaQ5I//qP2JAUpuTfKBWB3rxQqsdK94kD9ofltwg4N5fbUsfZsPleUuQULAxtdCBya2KY=}
