travis:
  secure:
    BINSTAR_TOKEN: X8PfINDI8F6EdVkqwlqb42qbazOQA4z95gB7mfX2MUKB5ovFHl69Qnz+2Zo93lsveEAvY05ESbNdoQmZM9zElwtcwVrl8nO2YXFhbku7NZ1Ctu2FT/AVG7SnXm3HVAueVlxHY93tPh3SuLAY/RWmGFQmRgK1EbaDBkvKvJ7fJ7GEUC1kidvK8XYVDo0JILKtMLNX0/o1Ct/1kBQixpHBUPdDPZJ9jpvjd0M52FzYk23hlDuSIkOJlQjMFaVLbXIUcdTSQU+eyHwBoqv3yk+ni1VO0UpzFLprwVB8OtK9m+l00K0xI4bCpxS0bc4bYL2kUp9Zk4LF3inxn51iiYNx6BL6rS0BNuLN3NtDK2AqXCefmfsxD48+p4odjMY4gscp9mLXGigWIXrJXjIbGomvZMFomX5Lhy1tVr9Pxh/qekQ5oW14NOtOuBkjOVM4rX3JaJOlSq8w0t5K5R01ColD/d1WtZt5SCifhmto8KrYfA2lby8elYtVh2Ca8TO2fxsZqp/c8ONXNaGx/Wk34+56CzmY9Z1uR1a1iPGG4isdWWXGEwnTq+Vv9ADCZJJT7L6a6xQolBoApXimGyIWBqo8wmB2zBDMlS+SWkvmPQKNAX4vBhJ7J+Aqpb+wPDGfQ/YJJs1x2r0gxlpdsjaQotGc10bUTIEWAAw9ST4W/iGBWgU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
